ora-server: 192.168.0.200
server:
  port: 9992
  servlet:
    context-path: /springboot-mybatisplus
  tomcat:
    uri-encoding: utf-8
spring:
  main:
    allow-bean-definition-overriding: true
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      enabled: true
      max-file-size: 2048MB
      max-request-size: 3000MB


  ######Druid数据源配置######
  datasource:
    #数据库连接url
    url: jdbc:oracle:thin:@${ora-server}:1521:ORCL
    #用户名
    username: gt_dzbp2
    #密码
    password: 123456
    #驱动名称
    driver-class-name: oracle.jdbc.OracleDriver
    name: _ApprovalDS
    #数据库连接池类型 druid
    type: com.alibaba.druid.pool.DruidDataSource
    # 连接池配置,下面配置说明请参考Druid Github Wiki，配置_DruidDataSource参考配置
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 1
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: "select 1 from dual"
      test-on-borrow: true
      test-on-return: false
      test-while-idle: false
      time-between-eviction-runs-millis: 60000
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"
        reset-enable: false
        login-username: admin
        login-password: 123456
        allow: localhost,127.0.0.1





